=== sebhero/XML_reader/teckning.dtd
<!-- rot-elementet teckning -->
<!ELEMENT teckning (farg?, ritobjekt*)>

<!-- elementet farg -->
<!ELEMENT farg EMPTY>
<!ATTLIST farg r CDATA #REQUIRED>
<!ATTLIST farg g CDATA #REQUIRED>
<!ATTLIST farg b CDATA #REQUIRED>

<!-- elementet ritobjekt -->
<!ELEMENT ritobjekt (punkt | linje | rektangel | oval)>

<!-- elementet punkt -->
<!ELEMENT punkt (farg?)>
<!ATTLIST punkt x CDATA #REQUIRED>
<!ATTLIST punkt y CDATA #REQUIRED>

<!-- elementet linje -->
<!ELEMENT linje (farg?)>
<!ATTLIST linje x CDATA #REQUIRED>
<!ATTLIST linje y CDATA #REQUIRED>
<!ATTLIST linje x2 CDATA #REQUIRED>
<!ATTLIST linje y2 CDATA #REQUIRED>

<!-- elementet rektangel -->
<!ELEMENT rektangel (farg?)>
<!ATTLIST rektangel x CDATA #REQUIRED>
<!ATTLIST rektangel y CDATA #REQUIRED>
<!ATTLIST rektangel bredd CDATA #REQUIRED>
<!ATTLIST rektangel hojd CDATA #REQUIRED>
<!ATTLIST rektangel fylld (ja | nej) "nej">

<!-- elementet oval -->
<!ELEMENT oval (farg?)>
<!ATTLIST oval x CDATA #REQUIRED>
<!ATTLIST oval y CDATA #REQUIRED>
<!ATTLIST oval bredd CDATA #REQUIRED>
<!ATTLIST oval hojd CDATA #REQUIRED>
<!ATTLIST oval fylld (ja | nej) "nej">

=== sebhero/XML_reader/teckning.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE teckning SYSTEM "teckning.dtd">

<teckning>
  <farg r="222" g="22" b="112"></farg>
  <ritobjekt>
    <punkt x="8" y="5">
      <farg r="2" g="33" b="3"></farg>
    </punkt>
  </ritobjekt>
  <ritobjekt>
    <linje x="18" y="15" x2="67" y2="677">
      <farg r="22" g="133" b="31"></farg>
    </linje>
  </ritobjekt>
  <ritobjekt>
    <rektangel x="80" y="55" bredd="56" hojd="65" fylld="ja">
      <farg r="88" g="88" b="200"></farg>
    </rektangel>
  </ritobjekt>
  <ritobjekt>
    <oval x="100" y="100" bredd="123" hojd="123">
    </oval>
  </ritobjekt>
  <ritobjekt>
    <rektangel x="20" y="155" bredd="156" hojd="65" fylld="nej">
      <farg r="10" g="100" b="0"></farg>
    </rektangel>
  </ritobjekt>
  <ritobjekt>
    <oval x="150" y="120" bredd="12" hojd="45" fylld="ja">
    </oval>
  </ritobjekt>
</teckning>
